In [202]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib


In [203]:
df = pd.read_csv('/content/train_u6lujuX_CVtuZ9i (1).csv')

In [204]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [205]:
df.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [206]:
df.shape

(614, 13)

In [207]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [209]:
df.sample(8)

Loan_ID Gender Married Dependents     Education Self_Employed  \
47   LP001144   Male     Yes          0      Graduate            No   
94   LP001325   Male      No          0  Not Graduate            No   
303  LP001977   Male     Yes          1      Graduate            No   
524  LP002697   Male      No          0      Graduate            No   
31   LP001095   Male      No          0      Graduate            No   
227  LP001758   Male     Yes          2      Graduate            No   
285  LP001924   Male      No          0      Graduate            No   
583  LP002898   Male     Yes          1      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
47              5821                0.0       144.0             360.0   
94              3620                0.0        25.0             120.0   
303             1625             1803.0        96.0             360.0   
524             4680             2087.0         NaN             360.0   
31              3167                0.0        74.0             360.0   
227             6250             1695.0       210.0             360.0   
285             3158             3053.0        89.0             360.0   
583             1880                0.0        61.0             360.0   

     Credit_History Property_Area Loan_Status  
47              1.0         Urban           Y  
94              1.0     Semiurban           Y  
303             1.0         Urban           Y  
524             1.0     Semiurban           N  
31              1.0         Urban           N  
227             1.0     Semiurban           Y  
285             1.0         Rural           Y  
583             NaN         Rural           N

In [210]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [211]:
df.isnull().sum().sum()

149

In [212]:
df = df.dropna()

In [213]:
df.isnull().sum().sum()

0

In [214]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [215]:
df.drop(['Loan_ID', 'Gender'], axis=1, inplace=True)

In [216]:
df.head()

Married Dependents     Education Self_Employed  ApplicantIncome  \
1     Yes          1      Graduate            No             4583   
2     Yes          0      Graduate           Yes             3000   
3     Yes          0  Not Graduate            No             2583   
4      No          0      Graduate            No             6000   
5     Yes          2      Graduate           Yes             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

  Property_Area Loan_Status  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y  
5         Urban           Y

In [217]:
df.replace({"Loan_Status":{'N':0,'Y':1}, 'Married':{'No':0,'Yes':1},'Gender':{'Male':1,'Female':0},'Self_Employed':{'No':0,'Yes':1},
                      'Property_Area':{'Rural':0,'Semiurban':1,'Urban':2},'Education':{'Graduate':1,'Not Graduate':0}},inplace=True)

In [218]:
df.head()

Married Dependents  Education  Self_Employed  ApplicantIncome  \
1        1          1          1              0             4583   
2        1          0          1              1             3000   
3        1          0          0              0             2583   
4        0          0          1              0             6000   
5        1          2          1              1             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

   Property_Area  Loan_Status  
1              0            0  
2              2            1  
3              2            1  
4              2            1  
5              2            1

In [219]:
df.Married.unique()

array([1, 0])

In [220]:
df.Dependents.unique()

array(['1', '0', '2', '3+'], dtype=object)

In [221]:
df.Dependents.replace("3+", "3", inplace=True)

In [222]:
df.Education.unique()

array([1, 0])

In [223]:
df.Self_Employed.unique()

array([0, 1])

In [224]:
df.Credit_History.unique()


array([1., 0.])

In [225]:
df.Property_Area.unique()

array([0, 2, 1])

In [226]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

In [227]:
print(X)
print(y)

     Married Dependents  Education  Self_Employed  ApplicantIncome  \
1          1          1          1              0             4583   
2          1          0          1              1             3000   
3          1          0          0              0             2583   
4          0          0          1              0             6000   
5          1          2          1              1             5417   
..       ...        ...        ...            ...              ...   
609        0          0          1              0             2900   
610        1          3          1              0             4106   
611        1          1          1              0             8072   
612        1          2          1              0             7583   
613        0          0          1              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0   
2              

In [228]:
scaler = StandardScaler()
scaler.fit(df)
scaled_data = scaler.transform(df)


In [229]:
print(scaled_data)

[[ 0.73716237  0.21859918  0.50325312 ...  0.41319694 -1.31886834
  -1.49774605]
 [ 0.73716237 -0.76203265  0.50325312 ...  0.41319694  1.25977445
   0.66766993]
 [ 0.73716237 -0.76203265 -1.98707162 ...  0.41319694  1.25977445
   0.66766993]
 ...
 [ 0.73716237  0.21859918  0.50325312 ...  0.41319694  1.25977445
   0.66766993]
 [ 0.73716237  1.19923101  0.50325312 ...  0.41319694  1.25977445
   0.66766993]
 [-1.35655324 -0.76203265  0.50325312 ... -2.42015348 -0.02954695
  -1.49774605]]


In [230]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 svc = SVC(kernel='rbf')

In [231]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (384, 10)
X_test shape: (96, 10)
y_train shape: (384,)
y_test shape: (96,)


In [232]:

svc = SVC(kernel='rbf')

svc.fit(X_train, y_train)

y_pred = svc.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)


In [236]:
print("SVC Accuracy:", accuracy)

SVC Accuracy: 0.78125


In [237]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=82)
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
accuracyy = accuracy_score(y_test, y_pred)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [238]:
print("LogisticRegression Accuracy:", accuracyy)

LogisticRegression Accuracy: 0.9166666666666666


In [239]:
class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.68      0.79        22
           1       0.91      0.99      0.95        74

    accuracy                           0.92        96
   macro avg       0.93      0.83      0.87        96
weighted avg       0.92      0.92      0.91        96

Confusion Matrix:
 [[15  7]
 [ 1 73]]


In [240]:
joblib.dump(log_reg, 'LogisticRegression.joblib')

['LogisticRegression.joblib']

In [241]:
joblib.dump(svc, 'support_vector_model.joblib')

['support_vector_model.joblib']